name: 'Download libs and detect JDK'
runs:
  using: 'composite'
  steps:
    - name: Download Linux library
      uses: actions/download-artifact@v6
      with:
        name: lib${{ env.LIB_NAME }}.so
        path: src/main/resources/natives/linux_64
    - name: Download Windows library
      uses: actions/download-artifact@v6
      with:
        name: ${{ env.LIB_NAME }}.dll
        path: src/main/resources/natives/windows_64
    - name: Download Mac OS library
      uses: actions/download-artifact@v6
      with:
        name: lib${{ env.LIB_NAME }}.dylib
        path: src/main/resources/natives/osx_arm64
    - name: Get JDK version from Maven project
      shell: bash
      run: |
        JDK_VERSION=$(mvn help:evaluate -Dexpression=maven.compiler.source -q -DforceStdout)
        echo "JDK_VERSION=$JDK_VERSION" >> $GITHUB_ENV
