name: Build Native

on:
  push:
    branches: [ "feature/add_native_build" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  LIB_NAME: clarabel_c

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          repository: oxfordcontrol/Clarabel.cpp
      - name: Install Eigen
        run: |
          sudo apt-get update
          sudo apt-get install -y libeigen3-dev
      - name: Build
        shell: bash
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" -S ./ -B ./build
          cmake --build ./build --target all
      - name: Upload library
        uses: actions/upload-artifact@v4
        with:
          name: lib${{ env.LIB_NAME }}.so
          path: rust_wrapper/target/release/lib${{ env.LIB_NAME }}.so
