name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_call:

env:
  LIB_NAME: clarabel_c

jobs:
  build-natives:
    uses: atraplet/clarabel4j-native/.github/workflows/build_natives.yml@master

  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    needs: [ build-natives ]
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/download-libs-and-detect-jdk
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JDK_VERSION }}
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean verify --file pom.xml
