name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_call:

env:
  LIB_NAME: clarabel_c

jobs:
  pre-build:
    runs-on: ubuntu-latest
    outputs:
      lib-version: ${{ steps.get-lib-version.outputs.lib-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Get natives library version from Maven project
        id: get-lib-version
        shell: bash
        run: |
          LIB_VERSION=$(mvn help:evaluate -Dexpression=natives.lib.version -q -DforceStdout)
          echo "lib-version=$LIB_VERSION" >> $GITHUB_OUTPUT

  build-natives:
    needs: [ pre-build ]
    uses: atraplet/clarabel4j-native/.github/workflows/build_natives.yml@master
    with:
      lib-version: ${{needs.pre-build.outputs.lib-version}}

  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    needs: [ build-natives ]
    steps:
      - uses: actions/checkout@v4
      - name: Download Linux library
        uses: actions/download-artifact@v4
        with:
          name: lib${{ env.LIB_NAME }}.so
          path: src/main/resources/natives/linux_64
      - name: Download Windows library
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.LIB_NAME }}.dll
          path: src/main/resources/natives/windows_64
      - name: Download Mac OS library
        uses: actions/download-artifact@v4
        with:
          name: lib${{ env.LIB_NAME }}.dylib
          path: src/main/resources/natives/osx_arm64
      - name: Get JDK version from Maven project
        shell: bash
        run: |
          JDK_VERSION=$(mvn help:evaluate -Dexpression=maven.compiler.source -q -DforceStdout)
          echo "JDK_VERSION=$JDK_VERSION" >> $GITHUB_ENV
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JDK_VERSION }}
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean verify --file pom.xml
