name: Build native

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          repository: oxfordcontrol/Clarabel.cpp
#          path: clarabelcpp
      - name: Install Eigen
        run: |
          sudo apt-get update
          sudo apt-get install -y libeigen3-dev
      - name: Build
        shell: bash
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" -S ./ -B ./build
          cmake --build ./build --target all
