name: Release

on:
  push:
    tags:
      - 'v*'

env:
  LIB_NAME: clarabel_c

jobs:
  build:
    uses: atraplet/clarabel4j-native/.github/workflows/build.yml@master

  release:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v5
      - name: Download Linux library
        uses: actions/download-artifact@v5
        with:
          name: lib${{ env.LIB_NAME }}.so
          path: src/main/resources/natives/linux_64
      - name: Download Windows library
        uses: actions/download-artifact@v5
        with:
          name: ${{ env.LIB_NAME }}.dll
          path: src/main/resources/natives/windows_64
      - name: Download Mac OS library
        uses: actions/download-artifact@v5
        with:
          name: lib${{ env.LIB_NAME }}.dylib
          path: src/main/resources/natives/osx_arm64
      - name: Get JDK version from Maven project
        run: |
          JDK_VERSION=$(mvn help:evaluate -Dexpression=maven.compiler.source -q -DforceStdout)
          echo "JDK_VERSION=$JDK_VERSION" >> $GITHUB_ENV
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JDK_VERSION }}
          distribution: 'temurin'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Publish to Maven Central
        run: mvn -B -DskipTests=true clean deploy -P release --file pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
